[package]
name = "mg-butane"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false
description = "Original experimental JavaScript engine"

[features]
default = []
modern = ["dep:boa_engine", "dep:boa_gc"]

[dependencies]
serde.workspace = true
boa_engine = { workspace = true, optional = true }
boa_gc = { workspace = true, optional = true }

[dev-dependencies]
serde_json.workspace = true
