[package]
name = "mg-sparkle"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
publish = false
description = "Original HTML, DOM, layout and Rust software rendering pipeline"

[dependencies]
mg-butane.workspace = true
serde.workspace = true
serde_json.workspace = true
url.workspace = true
image.workspace = true
fontdue.workspace = true
rustybuzz.workspace = true
