#!/usr/bin/env python3
"""Inventory the locked Linux graph and preserve upstream license/notice texts."""
import json
from pathlib import Path
import subprocess
import sys

metadata = json.loads(subprocess.check_output([
    "cargo", "metadata", "--locked", "--format-version", "1",
    "--filter-platform", "x86_64-unknown-linux-gnu",
]))
tree = subprocess.check_output([
    "cargo", "tree", "--locked", "--target", "x86_64-unknown-linux-gnu",
    "--edges", "normal,build", "--prefix", "none", "--format", "{p}",
], text=True)
active = {(line.split()[0], line.split()[1].removeprefix("v"))
          for line in tree.splitlines() if line.strip()}
out = ["mgbrowser dependency licenses : locked Linux x86_64 graph\n",
       "Active normal/build graph; not a claim that build tools are linked.\n"]
summary = ["# Locked dependency license inventory\n\n",
           "Generated by `tools/license-inventory.py` from Cargo.lock with the Linux x86_64 filter.\n",
           "Includes active normal/build dependencies, not only linked code. Upstream license/notice\n",
           "texts are preserved in the release archive's THIRD_PARTY_LICENSES.txt.\n\n",
           "| Package | Version | Declared license |\n| --- | --- | --- |\n"]
for package in sorted(metadata["packages"], key=lambda p: (p["name"], p["version"])):
    if (package["name"], package["version"]) not in active:
        continue
    if not package["license"]:
        raise SystemExit(f"Missing license expression: {package['name']}")
    out.append(f"\n{'=' * 72}\n{package['name']} {package['version']} | {package['license']}\n")
    out.append(f"Source: {package['source'] or 'https://github.com/pierce403/mgbrowser'}\n")
    summary.append(f"| {package['name']} | {package['version']} | {package['license']} |\n")
    root = Path(package["manifest_path"]).parent
    files = set()
    for pattern in ("LICENSE*", "LICENCE*", "COPYING*", "NOTICE*", "license*", "licenses/*"):
        files.update(p for p in root.glob(pattern) if p.is_file())
    if package.get("license_file"):
        files.add(root / package["license_file"])
    if not files:
        raise SystemExit(f"No license text found: {package['name']} ({root})")
    for path in sorted(files):
        out.append(f"\n--- {path.relative_to(root)} ---\n{path.read_text(errors='replace')}\n")
Path(sys.argv[1]).write_text("".join(out))
if len(sys.argv) > 2:
    Path(sys.argv[2]).write_text("".join(summary))
