#!/usr/bin/env python3
"""Inventory the locked Linux graph and preserve upstream license/notice texts."""
import json
from pathlib import Path
import subprocess
import sys

# These exact upstream releases declare a license but omit its text from the
# crate archive. Keep the reviewed fallback narrow: new omissions still fail.
MPL_ARCHIVE_OMISSIONS = {
    ("app_units", "0.7.8"), ("selectors", "0.40.0"),
    ("stylo", "0.21.0"), ("stylo_atoms", "0.21.0"),
    ("stylo_derive", "0.21.0"), ("stylo_dom", "0.21.0"),
    ("stylo_static_prefs", "0.21.0"), ("stylo_traits", "0.21.0"),
    ("to_shmem", "0.5.0"), ("to_shmem_derive", "0.1.0"),
}
LICENSE_INPUTS = Path(__file__).resolve().parent / "licenses"
BOA_ARCHIVE_OMISSIONS = {
    **{(name, "0.22.0"): "337a3668a0dc86dd401ea20906e782249a64a228"
       for name in ("boa_ast", "boa_engine", "boa_gc", "boa_interner",
                    "boa_macros", "boa_parser", "boa_string")},
    **{(name, "0.1.0"): "ad8739f5e0b51d20faf7a2cce98afa5c40121438"
       for name in ("small_btree", "tag_ptr")},
}

metadata = json.loads(subprocess.check_output([
    "cargo", "metadata", "--locked", "--format-version", "1",
    "--filter-platform", "x86_64-unknown-linux-gnu",
]))
tree = subprocess.check_output([
    "cargo", "tree", "--locked", "--target", "x86_64-unknown-linux-gnu",
    "--edges", "normal,build", "--prefix", "none", "--format", "{p}",
], text=True)
active = {(line.split()[0], line.split()[1].removeprefix("v"))
          for line in tree.splitlines() if line.strip()}
out = ["mgbrowser dependency licenses : locked Linux x86_64 graph\n",
       "Active normal/build graph; not a claim that build tools are linked.\n"]
summary = ["# Locked dependency license inventory\n\n",
           "Generated by `tools/license-inventory.py` from Cargo.lock with the Linux x86_64 filter.\n",
           "Includes active normal/build dependencies, not only linked code. Upstream license/notice\n",
           "texts are preserved in the release archive's THIRD_PARTY_LICENSES.txt.\n\n",
           "| Package | Version | Declared license |\n| --- | --- | --- |\n"]
for package in sorted(metadata["packages"], key=lambda p: (p["name"], p["version"])):
    if (package["name"], package["version"]) not in active:
        continue
    if not package["license"]:
        raise SystemExit(f"Missing license expression: {package['name']}")
    out.append(f"\n{'=' * 72}\n{package['name']} {package['version']} | {package['license']}\n")
    out.append(f"Source: {package['source'] or 'https://github.com/pierce403/mgbrowser'}\n")
    if (package["source"] or "").startswith("registry+"):
        out.append("Unmodified source archive (including MPL-covered source): "
                   f"https://crates.io/api/v1/crates/{package['name']}/{package['version']}/download\n")
    summary.append(f"| {package['name']} | {package['version']} | {package['license']} |\n")
    root = Path(package["manifest_path"]).parent
    files = set()
    for pattern in ("LICENSE*", "LICENCE*", "COPYING*", "NOTICE*", "license*", "licenses/*"):
        files.update(p for p in root.glob(pattern) if p.is_file())
    if package.get("license_file"):
        files.add(root / package["license_file"])
    if not files:
        key = (package["name"], package["version"])
        if key in MPL_ARCHIVE_OMISSIONS and package["license"] == "MPL-2.0":
            fallback = LICENSE_INPUTS / "MPL-2.0.txt"
        elif key == ("void", "1.0.2") and package["license"] == "MIT":
            fallback = LICENSE_INPUTS / "void-1.0.2-MIT.txt"
        elif key in BOA_ARCHIVE_OMISSIONS and package["license"] == "Unlicense OR MIT":
            vcs = json.loads((root / ".cargo_vcs_info.json").read_text())
            if vcs["git"]["sha1"] != BOA_ARCHIVE_OMISSIONS[key]:
                raise SystemExit(f"Unreviewed Boa license source revision: {key}")
            fallback = LICENSE_INPUTS / "boa-0.22-MIT.txt"
        else:
            raise SystemExit(f"No license text found: {package['name']} ({root})")
        out.append(f"\n--- Reviewed upstream text: {fallback.name} ---\n{fallback.read_text()}\n")
    for path in sorted(files):
        out.append(f"\n--- {path.relative_to(root)} ---\n{path.read_text(errors='replace')}\n")
Path(sys.argv[1]).write_text("".join(out))
if len(sys.argv) > 2:
    Path(sys.argv[2]).write_text("".join(summary))
